---
title: "merge"
author: "Esko"
date: "29.06.2016"
output: html_document
---

Merging two data frames 
========================

Next we will look how to merge to data frames,

Dataset
----------------

The first dataset is the game data described in the comparing groups page.
```{r}
game <- read.table("kr_game.txt", header=T)
```
The second dataset contains data from a working memory test for the participants. It has the following variables:
- player_id : the participant id
- pcu_score : Percentage Unit Score of a separate counting span working memory test. The higher the score, the higher the working memory capacity

```{r}
wmc <- read.table("kr_wmc.txt", header=T)
head(wmc)
```


Merging the data frame by the player_id
-------------------------------------------
```{r}
game.wmc <- merge(game, wmc, by="player_id")

head(game.wmc)
```

That was easy. I have named the new data frame as game.wmc, but any other name like gamewmc, would have been fine.

```{r}
write.table(game.wmc, "kr_gamewcm.txt", row.names=F)
```

